WITH RK AS (
        SELECT FI.ID
        , FN.FISH_NAME
        , FI.LENGTH
        , RANK() OVER (PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC) AS NUM
    FROM FISH_INFO FI
    JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
)

SELECT ID
    , FISH_NAME
    , LENGTH
FROM RK
WHERE NUM = 1
ORDER BY ID
