WITH ANIMAL_RANK AS (SELECT AI.ANIMAL_ID
        , AI.NAME
        , RANK() OVER (ORDER BY (AO.DATETIME - AI.DATETIME) DESC) AS RNK
    FROM ANIMAL_INS AI 
    JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID	= AO.ANIMAL_ID
)

SELECT ANIMAL_ID
    , NAME
FROM ANIMAL_RANK
WHERE RNK <= 2
