WITH MAX_VIEW AS (
    SELECT UGB.BOARD_ID
        , MAX(UGB.VIEWS) AS CNT
    FROM USED_GOODS_BOARD UGB
    JOIN USED_GOODS_FILE UGF ON UGB.BOARD_ID = UGF.BOARD_ID
    GROUP BY UGB.BOARD_ID
    ORDER BY CNT DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE 
WHERE BOARD_ID = (SELECT BOARD_ID FROM MAX_VIEW)
ORDER BY FILE_ID DESC
