WITH MAX_COUNT AS (
    SELECT MP.MEMBER_NAME
        , RR.REVIEW_TEXT
        , RR.REVIEW_DATE
        , RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
    FROM MEMBER_PROFILE MP
    JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID 
    GROUP BY MP.MEMBER_NAME
)


SELECT MP.MEMBER_NAME
        , RR.REVIEW_TEXT
        , RR.REVIEW_DATE
    FROM MEMBER_PROFILE MP
    JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_NAME IN (SELECT MEMBER_NAME FROM MAX_COUNT WHERE RNK = 1)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC
