WITH RECURSIVE TIME_LIST AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_LIST WHERE HOUR < 23
)

SELECT TL.HOUR
    , COUNT(AO.DATETIME) AS COUNT
FROM TIME_LIST TL
    LEFT JOIN ANIMAL_OUTS AO ON TL.HOUR = HOUR(AO.DATETIME) 
GROUP BY TL.HOUR
ORDER BY TL.HOUR
