WITH Rent_Cnt AS (
SELECT HISTORY_ID
    , CAR_ID
    , DATEDIFF(END_DATE, START_DATE) + 1 AS Diff
    , CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE NULL END AS Duration
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
)

SELECT RC.HISTORY_ID
    , FLOOR(CC.DAILY_FEE * RC.Diff * (1 - IFNULL(DP.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
LEFT JOIN Rent_Cnt RC ON CC.CAR_ID = RC.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON DP.DURATION_TYPE = RC.Duration AND DP.CAR_TYPE = CC.CAR_TYPE
WHERE CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, RC.HISTORY_ID DESC 
